### ISSUE TITLE
TODO LIST #1 (Работа с данными)

### ISSUE THREAD

**Issue by DenUP** [DenUP/TODO_LIST#1]
Решить проблему

- [x] Не работает отправка данных с TextField 
- [x] Сделать вывод данных в консоль из БД ( только для проверки)
- [x]  На главной странице сделать вывод всех категории
- [x] Откатить назад и еще раз проработать
- [x] Сделать удаление записи с помощью свайпа

**За сегодня сделано:**

1. Сверстал 2 экрана
2. Создал Сущность "Названия"
3. Сделал основы модуля для Второго экрана ( Ввод текста)

**Comment by DenUP** [comment]
###  Не работает отправка данных с TextField

3 часа не мог поймать баг. Ошибка была в том что я переключался на STL виджет при навигации, а не на STF

**Comment by DenUP** [comment]
Вчера 4 часа пытался понять почему не выводят данные в список ( все безуспешно) 

### Спасибо whois-kami 
https://github.com/DenUP/TODO_LIST/pull/2

За то что помог с кодом 
Нашел баг в моем коде 

Который я не мог поймать


### Сегодня

Встал в 4 утра
За 2:30 часа написал полностью рабочий код)) 


Интересно получается вчера ловил баг 3 часа, а сегодня уже за это время написал полностью рабочий код))
