### ISSUE TITLE
Создание TASK IN TODO #58 урок "часть 1"

### ISSUE THREAD

**Issue by DenUP** [DenUP/TODO_LIST#4]
![Image](https://github.com/DenUP/TODO_LIST/assets/88054229/c670d3df-d3c5-41c3-8bcf-22d1d2667f79)

### Создание новой сущности ( TASK)
_Что будет?_

- text - это название задачи
- bool isDone - выполнена или нет

- [x] Генерируем

Таски должны хранится в группах, поэтому в сущности группы добавляем
- [x] HaveList taks

### Часть Б: Создание шаблона и модели для Task_form
Навигаторы:

- [x] 'groups/tasks
- [x] 'groups/taksk/form

### Часть B:

**Как подключить переход с группы на конкретную задачу?**,

1. В модели группы, добавляем (groups_widget_model)

- [x] void showTaks, где добавляем context
- [x] добавляем его в title
- [x] добавляем функцию (индекс группы)
**Это плохой способ** т.к при удалении могут возникнуть баги, поэтому дополним:

- [x] Регистрируем адаптер
- [x] Октрываем бокс
- [x] Добавляем переменную groupkey, где будет обращаться к box.keAt по индексу
- [x] В навигаторе добавим arguments:groupkey

### Часть С:
**taks_widget**

- [x] Достаем роутер с параметром (groupkey)
Где его достать?

- [x] В didChange..., потому что этот метод будет вызываться каждый раз, когда меняется значение

**taks_widget_model**

Мы будем наследоваться от ChangeNotifier и Enherited т.к мы будем следить за обновлениями

- [x] В провайдер добавляем модель
- [x] Widget child
- [x] notifier: model
- [x] В нашу модель добавляем переменную groupkey

**taks_widget**

- [x] Прописываем модель делаем опционал.
- [x] В модели передаем значением groupkey
- [x] Верстаем шаблон

**taks_widget_model**

- [x] Создаем функцию _setup
- [x] Она должна вызываться после инициализации виджета
- [x] Регистрируем адаптер
- [x] Открываем бокс (_groupBox)
- [x] Делаем отложенную инциализацию _groupBox в конструкторе

_Зачем ?_

Потому что она будет вызывать разные методы, и они будут завязаны на _groupBox

- [x] Создать функцию _loadGroup
- [x] создаем переменную box
- [x] Задаем опциональной переменной значение "запрос" - "ключ Группы"
- [x] Вызываем нашу функцию в _setup
- [x] Делаем get запрос из приватной переменной
- [x] При переходе на таску делаем title имя группы

> 35:55

**Comment by DenUP** [comment]
Сегодня сделано 23 задачи из 31 

### Завтра

- [x] Сделать все сегодняшние таски
- [x] Откатиться назад и еще раз самому проработать весь код


![Screenshot of a comment on a GitHub issue showing an image, added in the Markdown, of an Octocat smiling and raising a tentacle.](
https://habrastorage.org/r/w1560/getpro/habr/upload_files/060/53d/8b6/06053d8b668c600ba3187e10ea54adcf.png
)

**Comment by DenUP** [comment]
Начало положено :)

![image](https://github.com/DenUP/TODO_LIST/assets/88054229/c271f7ae-56c0-4b61-aec1-b67662559ff8)

**Comment by DenUP** [comment]
Закомитил, все еще тяжеловато
