### ISSUE TITLE
Сохранение задачи в БД (TASK IN TODO #58_2)

### ISSUE THREAD

**Issue by DenUP** [DenUP/TODO_LIST#5]
Добавляем ТАСКИ В БазуДанных

### В модели добавляем (Task_form)

- [x] taskText
- [x] Регистрируем адаптер и открываем 2 бокса
- [x] В модели так же добавляем GroupKey
- [x] Также добавим новую задачу (Task)
- [x] Добавим задачу в боксТаск

В сущности Group

- [x] Void addTask
- [x] Проверим на null
- [x] В конструкторе добавим тип
- [x] В сущности task должен наследоваться от HiveObject
- [x] POP

**Comment by DenUP** [comment]
add commit
