### ISSUE TITLE
Допиливаем приложение todo #58_3

### ISSUE THREAD

**Issue by DenUP** [DenUP/TODO_LIST#6]
### Часть А:

- [x] Создание экрана для добавление задачи

- [x] В провайдере добавить, чтобы моделька не обновлялась 
- [x] Верстка экрана

![Image](https://github.com/DenUP/TODO_LIST/assets/88054229/78c00ee0-b38f-4ac7-86bc-e1da71c3bb70)

57:10

**Comment by DenUP** [comment]
Done`0

![Image](https://github.com/DenUP/TODO_LIST/assets/88054229/c7856726-c954-47fa-9d48-6ea6bf550039)

**Comment by DenUP** [comment]
### Сохранение, чтение, удаление тасков

**Comment by DenUP** [comment]
> - [x] Создать переменную где будут храниться таски <List> (private )
> - [x] Сделать гет запрос 
> - [x] Чтение тасков  **_readTask**
> - [x] Подписываться на изменения **_setupListenTasks**
> - [ ] Подписываться на изменение _readTask
> - [ ] **_setupListenTasks** слушать изменения только в группеКлючей
> - [ ] deleteTask



- [x] Создать переменную где будут храниться таски <List> (private )
- [x] Создать пуб переменную
- [x] **_readTask** ( смотреть за тасками, если null) то пустой лист и уведомлять подписчиков
- [x] **_setupListenTasks** - смореть(подписываться) на readTask 
- [x] **deleteTask** - удаляем по модели

**Comment by DenUP** [comment]
**Добавил иконки** если задача выполнена или нет. А так же добавил **стилизацию текста** при выполненной задачи
