### ISSUE TITLE
Основы работы с данными делаем todo лист, приводим в порядок навигацию - 59 урок

### ISSUE THREAD

**Issue by DenUP** [DenUP/TODO_LIST#7]
### Основы работы с данными делаем todo лист, приводим в порядок навигацию

**Часть А:**

- [x] Рефакторинг структуры кода UI
- [x] navigation
- [x] Создание путей к 
- [x] Создание абстрактного  класса для путей навигации
- [x] Правим пути навигации _в_ верстке
- [x] Переносим роутеры и главный роутер
